//---------------------------------------------------------------------------

#ifndef TIXMLH
#define TIXMLH
#include <vcl.h>
#include "pch.h"

#include <list>
#include <iterator>
#include <iostream.h>
#include <fstream.h>
#include "ipwxmlp.h"
//#ifndef TITaxSynH
//#include "TITaxSyn.h"
//#endif
#ifndef TICommonH
#include "TICommon.h"
#endif
#ifndef TIUtilsH
#include "TIUtils.h"
#endif

//#ifndef TGH
//#include "tg.h"
//#endif
//---------------------------------------------------------------------------

enum DECIMALSEPARATORS { COMMA=44, PERIOD=46 };
enum XMLBOOLSTYLE { ONE_ZERO, TRUE_FALSE };
//---------------------------------------------------------------------------

UnicodeString __fastcall InsertEntityRefs(UnicodeString&);
WideString __fastcall WInsertEntityRefs(WideString&);
WideString __fastcall WTranslateEntityRefs(WideString&);
UnicodeString __fastcall USFloatToStr(double);
UnicodeString __fastcall USFloatToStrF(double, TFloatFormat, int, int);
//---------------------------------------------------------------------------

class TAXAXML
{
public:
   UnicodeString XText;
   TAXAECOLGROUPS TaxaEcolGroup;
   CODENAME ecolgroup;
   TAXON taxon;
   UnicodeString SynonymName;
   int SynTaxonID;
   bool EcologicalGroups;
   bool TaxaGroup;
   bool EcologicalGroup;
   bool Code;
   bool Name;
   bool Author;
   bool Taxa;
   bool Taxon;
   bool EcolGroup;
   bool HigherID;
   bool Elements;
   bool Element;
   bool Units;
   bool Title;
   bool Synonyms;
   bool Synonym;
   bool TaxonID;
public:
   TAXAXML() {
	 EcologicalGroups = false;
	 TaxaGroup = false;
	 EcologicalGroup = false;
	 Code = false;
	 Name = false;
	 Author = false;
	 Taxa = false;
	 Taxon = false;
	 EcolGroup = false;
	 HigherID = false;
	 Elements = false;
	 Element = false;
	 Units = false;
	 Title = false;
	 Synonyms = false;
	 Synonym = false;
	 TaxonID = false;
	 }
};
//---------------------------------------------------------------------------

class TLXXML
{
public:
   UnicodeString XText;
   SYNONYMY Synonymy;
   bool Version;
   bool MajorVersion;
   bool MinorVersion;
   bool Release;
   bool SpreadSheet;
   bool Col;
   bool cell;
   bool text;
   bool value;
   bool date;
   bool formula;
   bool boolval;
   bool originalID;
   bool Synonym;
   bool TaxonName;
   bool ContribName;
   bool SynonymNotes;
   bool TaxonNotes;
   bool TaxonNotesIcon;
   bool Specimens;
   bool Specimen;
   bool Taphonomy;
   bool TaphType;
public:
   TLXXML() {
	 Version = false;
	 MajorVersion = false;
	 MinorVersion = false;
	 Release = false;
	 SpreadSheet = false;
	 Col = false;
	 cell = false;
	 text = false;
	 value = false;
	 date = false;
	 formula = false;
	 boolval = false;
	 originalID = false;
	 TaxonNotes = false;
	 TaxonName = false;
	 ContribName = false;
	 SynonymNotes = false;
	 TaxonNotesIcon = false;
	 Specimens = false;
	 Specimen = false;
	 Taphonomy = false;
	 TaphType = false;
	 Synonym = false;
	 }
};
//---------------------------------------------------------------------------

class TGXXML
{
public:
   UnicodeString XText;
   //LEVELS *InLev;
   bool Angle;
   bool AngleMarkerLabel;
   bool AutoMarkerBottom;
   bool AutoMarkerTop;
   bool AutoMax;
   bool AutoMin;
   bool AutoScale;
   bool AutoScaleFactor;
   bool AutoStepMultiplier;
   bool AutoTic;
   bool AutoTicDecPts;
   bool AutoBotDepth;
   bool AutoTopDepth;
   bool AutoX;
   bool AutoY;
   bool AxisAutoMax;
   bool AxisAutoMin;
   bool AxisColor;
   bool AxisLabelFont;
   bool AxisLength;
   bool AxisLineWidth;
   bool AxisMax;
   bool AxisMin;
   bool AxisStyle;
   bool AxisType;
   bool BackgroundColor;
   bool BarFill;
   bool BarPattern;
   bool BarWidth;
   bool Bold;
   bool Border;
   bool BorderColor;
   bool Bot;
   bool BotDepth;
   bool Bottom;
   bool BoundaryLineWidth;
   bool BoxStyle;
   bool BoxWidth;
   bool Center;
   bool CharSet;
   bool Cluster;
   bool Cluster1;
   bool Cluster2;
   bool Color;
   bool ColumnLineWidth;
   bool Component;
   bool Data;
   bool DataAutoMax;
   bool DataAutoMin;
   bool DataMax;
   bool DataMin;
   bool Date;
   bool DateAttr;
   bool DateBottom;
   bool DateFont;
   bool DateLabel;
   bool DatesPosition;
   bool DatesTitlePosition;
   bool DatesTitleTopYOffset;
   bool DateTitle;
   bool DateTitleFont;
   bool DateTop;
   bool DateVerticalOffset;
   bool DecimalPoints;
   bool DefaultColor;
   bool DefaultFont;
   bool DefaultSettings;
   bool DendAttr;
   bool DendAxisLabel1;
   bool DendAxisLabel2;
   bool DendAxisLabel3;
   bool DendAxisLabel4;
   bool DendColor;
   bool Dendrogram;
   bool DendrogramOrder;
   bool DendLineWidth;
   bool DendTitle;
   bool DendTitleFont;
   bool DendWidth;
   bool Depth;
   bool DepthBars;
   bool DepthBarsColor;
   bool DistanceToNextGraph;
   bool DO;
   bool DottedBaseLine;
   bool Exag;
   bool ExagColor;
   bool ExagFill;
   bool ExagGrid;
   bool ExagOutlineColor;
   bool ExagPattern;
   bool Font;
   bool FontHeight;
   bool FontName;
   bool FontStyle;
   bool Footer;
   bool Frame;
   bool FrameMargin;
   bool GraphColor;
   bool GraphNameAngle;
   bool GraphNameFont;
   bool GraphNameXOffset;
   bool GraphNameYOffset;
   bool GraphOutlineColor;
   bool Graph;
   bool Graphs;
   bool GraphStyle;
   bool GraphType;
   bool GraphWidth;
   bool Greek;
   bool GridLines;
   bool GridLineWidth;
   bool Group;
   bool GroupAttr;
   bool GroupCode;
   bool GroupCode1;
   bool GroupCode2;
   bool GroupFont;
   bool GroupName;
   bool GroupNamePosition;
   bool Header;
   bool HistogramLineWidth;
   bool Humo;
   bool ISS;
   bool Italic;
   bool KeyFont;
   bool KeyLineWidth;
   bool KeyOn;
   bool LabelAngle;
   bool LabeledTics;
   bool LabelFont;
   bool LabelOriginTic;
   bool LabelPosition;
   bool LabelToTicDistance;
   bool LabelYOffset;
   bool Left;
   bool Level;
   bool LineGraphLineWidth;
   bool LineStyle;
   bool LineWidth;
   bool LithAttr;
   bool LithCode;
   bool LithKey;
   bool LithLabel;
   bool LithLineWidth;
   bool LithTitle;
   bool LithTitleFont;
   bool LithUnit;
   bool Loaded;
   bool LoBound;
   bool LoBoundColor;
   bool MajorTicLength;
   bool MajorTics;
   bool MarkerLineWidth;
   bool MarkerType;
   bool MarkerSize;
   bool MinorTicLength;
   bool MinorTics;
   bool MSS;
   bool Name;
   bool Num;
   bool NumberFont;
   bool NumberOfLevels;
   bool On;
   bool Pattern;
   bool Plot;
   bool PlotGraphName;
   bool PlotZeroNumbers;
   bool PresenceSymbol;
   bool PrintTruncatedValues;
   bool Priority;
   bool RandomText;
   bool RareSpecies;
   bool Right;
   bool ScaleAutoMax;
   bool ScaleAutoMin;
   bool ScaleFactor;
   bool ScaleMax;
   bool ScaleMin;
   bool ScaleTruncatedValues;
   bool ScaleType;
   bool SilhouetteFill;
   bool SilhouetteLineWidth;
   bool SilhouettePattern;
   bool Size;
   bool SpaceRight;
   bool Status;
   bool Strikeout;
   bool Styles;
   bool Subscript;
   bool Superscript;
   bool Symbol;
   bool SymbolName;
   bool Text;
   bool TextFont;
   bool ThruLabelCol;
   bool TicDecPts;
   bool TicFont;
   bool TicLabelDivideBy;
   bool Top;
   bool TopDepth;
   bool TopTicLength;
   bool Truncate;
   bool TruncateDecPts;
   bool TruncateFont;
   bool TruncateWhere;
   bool TSS;
   bool Underline;
   bool Units;
   bool UserDefinedDash;
   bool UserDefinedSpace;
   bool UseThickVar;
   bool Value;
   bool VarCode;
   bool VarName;
   bool VerticalAxis;
   bool WSS;
   bool X;
   bool X_Title;
   bool Xaxes;
   bool XaxisDistance;
   bool XAxisLabel;
   bool XaxisMax;
   bool XaxisMin;
   bool XaxisStyle;
   bool XMarkerLabel;
   bool XPresence;
   bool XShift;
   bool Y;
   bool Y_Title;
   bool Yaxis;
   bool YAxisCode;
   bool YAxisLabel;
   bool YMarkerLabel;
   bool YShift;
   bool ZeroSymbol;
   bool Zone;
   bool ZoneAttr;
   bool ZoneBottom;
   bool ZoneColor;
   bool ZoneFont;
   bool ZoneLabel;
   bool ZoneLabelAttr;
   bool ZoneName;
   bool ZoneStyle;
   bool ZoneTitle;
   bool ZoneTitleAngle;
   bool ZoneTitleFont;
   bool ZoneTitleXOffset;
   bool ZoneTitleYOffset;
   bool ZoneTop;
   bool ZoneWidth;

public:
   TGXXML() {
	 Angle = false;
	 AngleMarkerLabel = false;
	 AutoMarkerBottom = false;
	 AutoMarkerTop = false;
	 AutoMax = false;
	 AutoMin = false;
	 AutoScale = false;
	 AutoScaleFactor = false;
	 AutoStepMultiplier = false;
	 AutoTic = false;
	 AutoTicDecPts = false;
	 AutoBotDepth = false;
	 AutoTopDepth = false;
	 AutoX = false;
	 AutoY = false;
	 AxisAutoMax = false;
	 AxisAutoMin = false;
	 AxisColor = false;
	 AxisLabelFont = false;
	 AxisLength = false;
	 AxisLineWidth = false;
	 AxisMax = false;
	 AxisMin = false;
     AxisStyle = false;
	 AxisType = false;
	 BackgroundColor = false;
	 BarFill = false;
	 BarPattern = false;
	 BarWidth = false;
	 Bold = false;
	 Border = false;
	 BorderColor = false;
	 Bot = false;
	 BotDepth = false;
	 Bottom = false;
	 BoundaryLineWidth = false;
	 BoxStyle = false;
	 BoxWidth = false;
	 Center = false;
	 CharSet = false;
	 Cluster = false;
	 Cluster1 = false;
	 Cluster2 = false;
	 Color = false;
	 ColumnLineWidth = false;
	 Component = false;
	 Data = false;
	 DataAutoMax = false;
	 DataAutoMin = false;
	 DataMax = false;
	 DataMin = false;
	 Date = false;
	 DateAttr = false;
	 DateBottom = false;
	 DateFont = false;
	 DateLabel = false;
	 DatesPosition = false;
	 DatesTitlePosition = false;
	 DatesTitleTopYOffset = false;
	 DateTitle = false;
	 DateTitleFont = false;
	 DateTop = false;
	 DateVerticalOffset = false;
	 DecimalPoints = false;
	 DefaultColor = false;
	 DefaultFont = false;
	 DefaultSettings = false;
	 DendAttr = false;
	 DendAxisLabel1 = false;
	 DendAxisLabel2 = false;
	 DendAxisLabel3 = false;
	 DendAxisLabel4 = false;
	 DendColor = false;
	 DendLineWidth = false;
	 Dendrogram = false;
	 DendrogramOrder = false;
	 DendTitle = false;
	 DendTitleFont = false;
	 DendWidth = false;
	 Depth = false;
	 DepthBars = false;
	 DepthBarsColor = false;
	 DistanceToNextGraph = false;
	 DO = false;
	 DottedBaseLine = false;
	 Exag = false;
	 ExagColor = false;
	 ExagFill = false;
	 ExagGrid = false;
	 ExagOutlineColor = false;
	 ExagPattern = false;
	 Font = false;
	 FontHeight = false;
	 FontName = false;
	 FontStyle = false;
	 Footer = false;
	 Frame = false;
	 FrameMargin = false;
	 GraphColor = false;
	 GraphNameAngle = false;
	 GraphNameFont = false;
	 GraphNameXOffset = false;
	 GraphNameYOffset = false;
	 GraphOutlineColor = false;
	 Graph = false;
	 Graphs = false;
	 GraphStyle = false;
	 GraphType = false;
	 GraphWidth = false;
	 Greek = false;
	 GridLines = false;
	 GridLineWidth = false;
	 Group = false;
	 GroupAttr = false;
	 GroupCode = false;
	 GroupCode1 = false;
	 GroupCode2 = false;
	 GroupFont = false;
	 GroupName = false;
	 GroupNamePosition = false;
	 Header = false;
	 HistogramLineWidth = false;
	 Humo = false;
	 ISS = false;
	 Italic = false;
	 KeyFont = false;
	 KeyLineWidth = false;
	 KeyOn = false;
	 LabelAngle = false;
	 LabeledTics = false;
	 LabelFont = false;
	 LabelOriginTic = false;
	 LabelPosition = false;
	 LabelToTicDistance = false;
	 LabelYOffset = false;
	 Left = false;
	 Level = false;
	 LineGraphLineWidth = false;
	 LineStyle = false;
	 LineWidth = false;
	 LithAttr = false;
	 LithCode = false;
	 LithKey = false;
	 LithLabel = false;
	 LithLineWidth = false;
	 LithTitle = false;
	 LithTitleFont = false;
	 LithUnit = false;
	 Loaded = false;
	 LoBound = false;
	 LoBoundColor = false;
	 MajorTicLength = false;
	 MajorTics = false;
	 MarkerLineWidth = false;
	 MarkerType = false;
	 MarkerSize = false;
	 MinorTicLength = false;
	 MinorTics = false;
	 MSS = false;
	 Name = false;
	 Num = false;
	 NumberFont = false;
	 NumberOfLevels = false;
	 On = false;
	 Pattern = false;
	 Plot = false;
	 PlotGraphName = false;
	 PlotZeroNumbers = false;
	 PresenceSymbol = false;
	 PrintTruncatedValues = false;
	 Priority = false;
	 RandomText = false;
	 RareSpecies = false;
	 Right = false;
	 ScaleAutoMax = false;
	 ScaleAutoMin = false;
	 ScaleFactor = false;
	 ScaleMax = false;
	 ScaleMin = false;
	 ScaleTruncatedValues = false;
	 ScaleType = false;
	 SilhouetteFill = false;
	 SilhouetteLineWidth = false;
	 SilhouettePattern = false;
	 Size = false;
	 SpaceRight = false;
	 Status = false;
	 Strikeout = false;
	 Styles = false;
	 Subscript = false;
	 Superscript = false;
	 Symbol = false;
	 SymbolName = false;
	 Text = false;
	 TextFont = false;
	 ThruLabelCol = false;
	 TicDecPts = false;
	 TicFont = false;
	 TicLabelDivideBy = false;
	 Top = false;
	 TopDepth = false;
	 TopTicLength = false;
	 Truncate = false;
	 TruncateDecPts = false;
	 TruncateFont = false;
	 TruncateWhere = false;
	 TSS = false;
	 Underline = false;
	 Units = false;
	 UserDefinedDash = false;
	 UserDefinedSpace = false;
	 UseThickVar = false;
	 Value = false;
	 VarCode = false;
	 VarName = false;
	 VerticalAxis = false;
	 WSS = false;
	 X = false;
	 X_Title = false;
	 Xaxes = false;
	 XaxisDistance = false;
	 XAxisLabel = false;
	 XaxisMax = false;
	 XaxisMin = false;
	 XaxisStyle = false;
	 XMarkerLabel = false;
	 XPresence = false;
	 XShift = false;
	 Y = false;
	 Y_Title = false;
	 Yaxis = false;
	 YAxisCode = false;
	 YAxisLabel = false;
	 YMarkerLabel = false;
	 YShift = false;
	 ZeroSymbol = false;
	 Zone = false;
	 ZoneAttr = false;
	 ZoneBottom = false;
	 ZoneColor = false;
	 ZoneFont = false;
	 ZoneLabel = false;
	 ZoneLabelAttr = false;
	 ZoneName = false;
	 ZoneStyle = false;
	 ZoneTitle = false;
	 ZoneTitleAngle = false;
	 ZoneTitleFont = false;
	 ZoneTitleXOffset = false;
	 ZoneTitleYOffset = false;
	 ZoneTop = false;
	 ZoneWidth = false;
	 }
};
//---------------------------------------------------------------------------

class DGXXML
{
public:
   UnicodeString XText;
   bool Cluster;
   bool Cluster1;
   bool Cluster2;
   bool CONISS;
   bool Dendrogram;
   bool DendrogramOrder;
   bool DO;
   bool ISS;
   bool MSS;
   bool TSS;
   bool WSS;
public:
   DGXXML() {
	 Cluster = false;
	 Cluster1 = false;
	 Cluster2 = false;
	 CONISS = false;
	 Dendrogram = false;
	 DendrogramOrder = false;
     DO = false;
	 ISS = false;
	 MSS = false;
	 TSS = false;
	 WSS = false;
	 }
};
//---------------------------------------------------------------------------

#endif
