#define (No assigned Map IDs)	0
#define IDH_Introduction	1
#define IDH_Silhouette_Graph_Exaggeration	5
#define IDH_Line_Width_Combo_Box	6
#define IDH_Silhouette_Dotted_Vertical_Axis	8
#define IDH_Silhouette_Depth_Bars	9
#define IDH_Silhouette_Fill_Style	4
#define IDH_Pattern_Dialog_Box	10
#define IDH_Silhouette_Graph	11
#define IDH_Select_Variables	12
#define IDH_Graph_Style_Dialog_Box	3
#define IDH_Greek_Letters	2
#define IDH_Histogram_Style	13
#define IDH_Histogram_Graph	14
#define IDH_Color_List_Box	7
#define IDH_Histogram_Vertical_Axis	15
#define IDH_Line_Graph_Symbols	16
#define IDH_Line_Graph_Symbol_Size	17
#define IDH_Line_Graph_Symbol_Labels	18
#define IDH_Line_Graph_Zero_Symbols	19
#define IDH_Font_Dialog_Box	20
#define IDH_Numbers_Graph	21
#define IDH_Presence_Graph	22
#define IDH_Presence_Graph_Position	23
#define IDH_Presence_Graph_Label	24
#define IDH_Exporting_a_diagram	25
#define IDH_Xaxes_Dialog_Box	26
#define IDH_Xaxis_Length	27
#define IDH_Xaxis_Minimum_Limit	28
#define IDH_Xaxis_Maximum_Limit	29
#define IDH_Space_Between_Graphs	30
#define IDH_Xaxis_Label	31
#define IDH_Xaxis_Tic_Mark_Step_Size	32
#define IDH_Axis_Tic_Mark_Distance	33
#define IDH_Axis_Tic_Mark_Decimal_Points	35
#define IDH_Xaxis_Label_Origin	36
#define IDH_Xaxis_Tic_Mark_Lengths	37
#define IDH_Xaxis_Grid_Lines	38
#define IDH_Xaxis_Options	39
#define IDH_Xaxis_Tic_Marks	40
#define IDH_Xaxis_Name	41
#define IDH_Xaxis_Name_Angle	42
#define IDH_Xaxis_Name_X_Offset	43
#define IDH_Xaxis_Name_Center	44
#define IDH_Xaxis_Name_Y_Offset	45
#define IDH_Xaxis_Truncate	46
#define IDH_Xaxis_Truncate_Where	47
#define IDH_Xaxis_Truncate_Print	48
#define IDH_Graph_Style_Button	49
#define IDH_Xaxes_Button	50
#define IDH_Yaxis_Dialog_Box	51
#define IDH_Select_Yaxes	52
#define IDH_Yaxis_Limits	53
#define IDH_Yaxis_Style	54
#define IDH_Yaxis_Length	55
#define IDH_Yaxis_Xaxis_Space	56
#define IDH_Yaxis_Space	57
#define IDH_Yaxis_Tic_Marks	58
#define IDH_Yaxis_Step_Size	59
#define IDH_Yaxis_Tic_Mark_Lengths	60
#define IDH_Axis_Tic_Mark_Divide_By	34
#define IDH_Yaxis_Labels	61
#define IDH_Yaxis_Label_Position	62
#define IDH_Yaxis_Label_Coordinates	63
#define IDH_Yaxis_Label_Angle	64
#define IDH_Yaxis_Properties	65
#define IDH_Y_axis_Properties_Apply_To_All_Scales	66
#define IDH_Variables_Dialog_Box	67
#define IDH_Variables_Down_Arrow	68
#define IDH_Variable_Up_Arrow	69
#define IDH_Changing_Variable_Order	70
#define IDH_Variables_Overlay	71
#define IDH_Variables_Stack	72
#define IDH_Variables_Skip	73
#define IDH_Variables_Names_Format	74
#define IDH_Groups_Dialog_Box	75
#define IDH_Group_Options	76
#define IDH_Group_Text_Position	77
#define IDH_Groups_Apply_to_All	78
#define IDH_Zones_Dialog_Box	79
#define IDH_Zone_Levels	80
#define IDH_Zone_Labels	81
#define IDH_Zone_Column_Title	82
#define IDH_Zone_Column_Title_Text_Box	83
#define IDH_Zone_Column_Title_Angle	84
#define IDH_Zone_Column_Label_X_Offset	85
#define IDH_Zone_Column_Label_Center	86
#define IDH_Zone_Column_Label_Y_Offset	87
#define IDH_Zone_Line_Options	88
#define IDH_Zone_Line_Dash_and_Space_Width	89
#define IDH_Zones_Apply_to_All_Line_Zones	90
#define IDH_Select_Zone_Line_Style	91
#define IDH_Zone_Screen_Options	92
#define IDH_Zone_Screen_Style	93
#define IDH_Zone_Screen_Dash_and_Space_Width	94
#define IDH_Zone_Screen_Width	95
#define IDH_Zone_Screen_Borders	96
#define IDH_Zones_Apply_to_all_Screen_Zones	97
#define IDH_Dates_Dialog_Box	98
#define IDH_Dates_Plus_or_Minus_Button	99
#define IDH_Dates_Label	100
#define IDH_Dates_Label_Postion	101
#define IDH_Dates_User_Defined_Coordinates	102
#define IDH_Text_Dialog_Box	103
#define IDH_Text_Header_Footer	104
#define IDH_Font_Formatting	105
#define IDH_Text_Header_Hint	106
#define IDH_Text_Header_X_Coordinate	107
#define IDH_Text_Header_Y_Coordinate	108
#define IDH_Text_Footer_Hint	109
#define IDH_Text_Footer_X_Coordinate	110
#define IDH_Text_Footer_Y_Coordinate	111
#define IDH_Random_Text	112
#define IDH_Text_Interactive	113
#define IDH_Colors_Dialog_Box	114
#define IDH_Line_Width_Dialog_Box	115
#define IDH_Printing	116
#define IDH_Printing_Overlap	117
#define IDH_Printing_Specify_Diagram_Height	118
#define IDH_Printing_Specify_Yaxis_Height	119
#define IDH_Printing_Units	120
#define IDH_Printing_Orientation	121
#define IDH_Italics_Dialog_Box	122
#define IDH_Frame_Dialog_Box	123
#define IDH_Frame_Draw_Checkbox	124
#define IDH_Frame_Margin	125
#define IDH_Frame_Page_Margins	126
#define IDH_Rare_Types_Dialog_Box	127
#define IDH_Rare_Symbol	128
#define IDH_Rare_Symbol_Size	129
#define IDH_Cluster_Analysis_Dialog_Box	130
#define IDH_Cluster_Analysis_Dendrogram_Scale	131
#define IDH_Cluster_Analysis_Axis_Label	132
#define IDH_Cluster_Analysis_Title	133
#define IDH_Cluster_Analysis_Dendrogram_Width	134
#define IDH_Cluster_Analysis_Tic_Mark_Step_Size	135
#define IDH_Cluster_Analysis_Tic_Mark_Labels	136
#define IDH_Cluster_Analysis_Tic_Mark_Lengths	137
#define IDH_Cluster_Analysis_Plot_Dendrogram	138
#define IDH_Cluster_Analysis_Open_dgx_file	139
#define IDH_Cluster_Analysis_Run_CONISS	140
#define IDH_Lithology_Dialog_Box	141
#define IDH_Lithology_Design_Component_Tab_Sheet	145
#define IDH_Lithology_Design_Shift_Pad	143
#define IDH_Lithology_Design_Unit_Worksheet	144
#define IDH_Lithology_Design_Example	142
#define IDH_Lithology_Options_Key_Worksheet	146
#define IDH_Lithology_Options_Import_Components	147
#define IDH_Lithology_Options_Plot_Column	148
#define IDH_Lithology_Options_Plot_Key	149
#define IDH_Lithology_Options_Key_Box_Width	150
#define IDH_Lithology_Options_Column_Depth	151
#define IDH_Lithology_Options_Lithology_Title	152
#define IDH_Lithology_Options_Title_Angle	153
